pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Assemble') {
            steps {
                dir('spring-example') {
                    sh 'chmod +x gradlew || true'
                    sh './gradlew clean build -x test'
                }
            }
        }

        stage('Test') {
            steps {
                dir('spring-example') {
                    sh './gradlew test'
                    junit 'build/test-results/test/*.xml'
                }
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'spring-example/build/libs/*.jar', fingerprint: true
            }
        }

        stage('Deploy to Production?') {
            steps {
                script {
                    def approval = input(
                        message: "Deploy to GREEN VM?",
                        parameters: [choice(name: 'confirm', choices: "no\nyes", description: 'Approve deployment?')]
                    )
                    if (approval == "no") {
                        error "Deployment aborted by user"
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    def artifact = sh(
                        script: "ls spring-example/build/libs/*.jar",
                        returnStdout: true
                    ).trim()

                    echo "Artifact encontrado: ${artifact}"

                    def onlyName = artifact.replace("spring-example/build/libs/", "")
                    def artifact_url = "${env.BUILD_URL}artifact/spring-example/build/libs/${onlyName}"

                    echo "Artifact URL: ${artifact_url}"

                    sh """
                    wsl ansible-playbook ansible/deploy-green.yml \
                    -i inventory.ini \
                    --extra-vars "artifact_url=${artifact_url}"
                    """
                }
            }
        }

        stage('Verify Deployment') {
            steps {
                sh "wsl ./scripts/healthcheck.sh"
            }
        }
    }

    post {
        success {
            echo 'Pipeline succeeded'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}
