pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Assemble') {
            steps {
                sh './gradlew clean build -x test'
            }
        }

        stage('Test') {
            steps {
                sh './gradlew test'
                junit 'build/test-results/test/*.xml'
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'build/libs/*.jar', fingerprint: true
            }
        }

        stage('Deploy to Production?') {
            steps {
                script {
                    def approval = input(
                        message: "Deploy to GREEN VM?",
                        parameters: [choice(name: 'confirm', choices: "no\nyes", description: 'Approve?')]
                    )
                    if (approval == "no") {
                        error "Deployment aborted by user"
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                wsl ansible-playbook ansible/deploy-green.yml \
                -i inventory.ini \
                --extra-vars "artifact_url=http://YOUR-JENKINS/artifact.jar"
                '''
            }
        }

        stage('Verify Deployment') {
            steps {
                sh "wsl ./scripts/healthcheck.sh"
            }
        }

    }

    post {
        success {
            sh """
            git tag -a stable-v${env.BUILD_NUMBER} -m 'Stable build'
            git push origin stable-v${env.BUILD_NUMBER}
            """
            echo "Pipeline finished successfully"
        }
        failure {
            echo "Pipeline failed"
        }
    }
}
