# CA4 – Vagrant + Ansible (Ubuntu 22.04)
Vagrant.configure("2") do |config|
  # Box Ubuntu 22.04 (Jammy). Corrige o comentário: 22.04 ≠ 20.04
  config.vm.box = "ubuntu/jammy64"
  config.ssh.forward_agent = true

  # ===== DB VM =====
  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.10"
    db.vm.synced_folder ".", "/project"
  end

  # ===== APP VM =====
  config.vm.define "app" do |app|
    app.vm.hostname = "app"
    app.vm.network "private_network", ip: "192.168.56.11"
    app.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
    app.vm.synced_folder ".", "/project"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/site.yml"
    ansible.limit    = "all"
    ansible.verbose  = "v"

    ansible.extra_vars = {
      # DB
      db_host:      "192.168.56.10",
      db_port:      9092,
      db_base_dir:  "/project/h2db",

      # APP
      app_port:     8080,
      app_repo_ssh: "git@github.com:alexvieira7/cogsi2526-1211551-1250559-1250497.git",
      app_repo_dir: "/home/vagrant/repo",
      app_subpath:  "CA2/CA2-part2/rest",
      auto_start:   true,
      app_host:     "192.168.56.11"
    }
  end
end
