Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # VM BLUE
  config.vm.define "blue" do |blue|
    blue.vm.hostname = "blue"
    blue.vm.network "private_network", ip: "192.168.56.10"
    blue.vm.provider "virtualbox" do |vb|
      vb.name = "ca6-blue"
      vb.memory = 1024
    end
  end

  # VM GREEN
  config.vm.define "green" do |green|
    green.vm.hostname = "green"
    green.vm.network "private_network", ip: "192.168.56.11"
    green.vm.provider "virtualbox" do |vb|
      vb.name = "ca6-green"
      vb.memory = 1024
    end
  end
end
