# CA4 – Vagrant + Chef (Ubuntu 22.04)
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.ssh.forward_agent = true

  # ===== DB VM =====
  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.10"
    db.vm.synced_folder ".", "/project"

    # Provisionamento com Chef
    db.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "cookbooks"
      chef.chef_license = "accept"  # <--- linha adicionada
      chef.add_recipe "h2"
      chef.add_recipe "users"
      chef.add_recipe "pam"
      chef.add_recipe "healthcheck"
    end
  end

  # ===== APP VM =====
  config.vm.define "app" do |app|
    app.vm.hostname = "app"
    app.vm.network "private_network", ip: "192.168.56.11"
    app.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
    app.vm.synced_folder ".", "/project"

    # Provisionamento com Chef
    app.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "cookbooks"
      chef.chef_license = "accept"  # <--- linha adicionada
      chef.add_recipe "spring_app"
      chef.add_recipe "users"
      chef.add_recipe "pam"
      chef.add_recipe "healthcheck"
    end
  end
end
