Vagrant.configure("2") do |config|

  config.vm.define "production" do |prod|
    prod.vm.box = "ubuntu/focal64"
    prod.vm.network "private_network", ip: "192.168.57.10"
    prod.vm.hostname = "prod"

    prod.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
    end

    prod.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
    SHELL
  end
end
