pipeline {

    agent any

    environment {
        DOCKER_USER = credentials('dockerhub-username')  
        DOCKER_PASS = credentials('dockerhub-password')
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Assemble') {
            steps {
                dir('CA6/CA6-part2/spring-example') {
                    sh 'chmod +x gradlew || true'
                    sh './gradlew clean build'
                }
            }
        }

        stage('Parallel Tests') {
            parallel {

                stage('Unit Tests') {
                    steps {
                        dir('CA6/CA6-part2/spring-example') {
                            sh './gradlew test'
                            junit 'build/test-results/test/**/*.xml'
                        }
                    }
                }

                stage('Integration Tests') {
                    steps {
                        dir('CA6/CA6-part2/spring-example') {
                            sh './gradlew integrationTest'
                            junit 'build/test-results/integrationTest/**/*.xml'
                        }
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    def IMAGE_TAG = "build-${env.BUILD_NUMBER}"

                    sh """
                        cd CA6/CA6-part2
                        docker build -t ${env.DOCKER_USER_USR}/spring-rest-app:${IMAGE_TAG} .
                        docker tag ${env.DOCKER_USER_USR}/spring-rest-app:${IMAGE_TAG} ${env.DOCKER_USER_USR}/spring-rest-app:latest
                    """
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    sh """
                        echo "${env.DOCKER_USER_PSW}" | docker login -u "${env.DOCKER_USER_USR}" --password-stdin
                        docker push ${env.DOCKER_USER_USR}/spring-rest-app:${IMAGE_TAG}
                        docker push ${env.DOCKER_USER_USR}/spring-rest-app:latest
                    """
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline concluída com sucesso!"
        }
        failure {
            echo "Pipeline falhou!"
        }
    }
}
