Vagrant.configure("2") do |config|

  config.vm.define "lb" do |lb|
    lb.vm.box = "ubuntu/jammy64"
    lb.vm.hostname = "lb"

    lb.vm.network "private_network", ip: "192.168.56.30"

    lb.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    lb.vm.provision "shell", inline: <<-SHELL
      apt-get update -y
      apt-get install haproxy -y
    SHELL

  end

end
